# Generated by Django 4.2.5 on 2024-01-21 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='subcounty',
            options={'verbose_name_plural': 'Sub Counties'},
        ),
        migrations.AlterModelOptions(
            name='unitareaofinsurance',
            options={'verbose_name_plural': 'Unit Area of Insurance'},
        ),
        migrations.CreateModel(
            name='InsuranceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.DecimalField(decimal_places=8, max_digits=16)),
                ('bag_price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('sum_insured', models.DecimalField(decimal_places=8, max_digits=16)),
                ('actual_premium', models.DecimalField(decimal_places=8, max_digits=16)),
                ('rounded_premium', models.DecimalField(decimal_places=8, max_digits=16)),
                ('gok_premium_subsidy', models.DecimalField(decimal_places=8, max_digits=16)),
                ('farmer_premium', models.DecimalField(decimal_places=8, max_digits=16)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.county')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.subcounty')),
                ('uai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.unitareaofinsurance')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.village')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ward')),
            ],
        ),
    ]
